
create TABLE city (
	id bigint generated by default as identity,
	country varchar(256),
	name varchar(256),
	state varchar(256),
	map varchar(256)
);

create table ohrm_role(
id bigint generated by default as identity,
name varchar(50),
organization_id int,
status enum('Active','Inactive'),
created_at date,
PRIMARY KEY(id),
UNIQUE(name));


create TABLE ohrm_users(
	id bigint generated by default as identity,
	firstname varchar(20),
	lastname varchar(20),
	middlename varchar(20),
	user_role varchar(50),
	FOREIGN KEY (user_role)
	REFERENCES ohrm_role(id),
	username varchar(25),
	password varchar(50),
	status enum('Active','InActive'),
	organization_id int,
	employee_id varchar(20),
	employee_photo varchar(100),
	gender enum('Male','Female'),
	marital_status enum('Single','Married'),
	dob date,
	country varchar(50),
		PRIMARY KEY(id));

	create TABLE ohrm_organization(
	id bigint generated by default as identity,
	name varchar(50),
	tax_id varchar(30),
	registration_number varchar(30),
	phone varchar(15),
	fax varchar(15),
	email varchar(30),
	country varchar(30),
	state varchar(50),
	city varchar(50),
	zip_code varchar(20),
	street1 varchar(100),
	street2 varchar(100),
	note varchar(250),
	created_at date,
	PRIMARY KEY(id)
	);
	

create table ohrm_section(
id bigint generated by default as identity,
name varchar(50),
organization_id int,
created_at date,
PRIMARY KEY(id),
UNIQUE(name)
);

create table ohrm_user_permissions(
id bigint generated by default as identity,
role_id int,
organization_id int,
section_id int,
can_read enum('Y','N'),
can_write enum('Y','N'),
can_delete enum('Y','N'),
created_at date,
PRIMARY KEY(id)
);


/*create TABLE user(	
	id bigint generated by default as identity,
	firstname varchar(20),
	lastname varchar(20),
	PRIMARY KEY(id))*/

/*	
	  FOREIGN KEY REFERENCES organization(id)
	  FOREIGN KEY REFERENCES organization(id)
	  FOREIGN KEY REFERENCES role(name)
*/